services:
  network-deploy-service:
    networks:
      - eazybank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: suayb/bitnami-debezium-postgresql:15.4.0
    healthcheck:
      test: pg_isready -U postgres
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRESQL_PASSWORD: root

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod, docker
      SPRING_CONFIG_IMPORT: configserver:http://easybank:root@config-server:8071/
#      SPRING_DATASOURCE_USERNAME: easybank
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_DATA_REDIS_PORT: 6379
#      SPRING_DATA_REDIS_PASSWORD: d41d8cd98f00b204e9800998ecf8427e
#      SPRING_DATA_REDIS_TIMEOUT: 1s

  microservice-eureka-config:
    extends:
      service: microservice-config-server-config
    depends_on:
      eureka-server:
        condition: service_healthy